### ISSUE TITLE
Reddit Results returning twice in the view (due to the model)

### ISSUE THREAD

**Issue by ummerr** [ummerr/moose_talk#35]
Hey guys, I was just doing some bug testing and it appears that we are displaying 2 sets of reddit links

![image](https://cloud.githubusercontent.com/assets/2242572/5792976/6ec06b0e-9eff-11e4-82fe-91aaee42229d.png)

Jay - this appears to be coming from the RedditSearches association for an individual search.  I took a screenshot of the console investigation below.

![image](https://cloud.githubusercontent.com/assets/2242572/5792984/c51ec068-9eff-11e4-957a-c79a57c0397c.png)

**Comment by planarian** [comment]
Yeah, I'm aware of the problem, but I'm still not able to run the site 
on my machine. (see screenshot)

**Comment by planarian** [comment]
Hi guys,

I wasn't planning on coming in today, but if anyone's currently there, 
I'll be there ASAP.

Thanks,

Jay

**Comment by ummerr** [comment]
There's no screenshot attached.

**Comment by planarian** [comment]
@ummerr

Not sure why it didn't go through. Trying again

sinatra error

**Comment by ummerr** [comment]
Still not going through (can't view the screenshot)

@planarian I wrote out a new README file which I did a pull request for.  There may be some help there?
